---
deployment:
  tasks:
    - export DEPLOYPATH=/home/devctlwr/public_html/
    - /bin/cp src/index.html $DEPLOYPATH
    - /bin/cp src/index.js $DEPLOYPATH
    - /bin/cp src/styles/style.css $DEPLOYPATH
    - /bin/cp src/styles/style.sass $DEPLOYPATH
    - /bin/cp src/styles/style.scss $DEPLOYPATH